name: Build game

on:
  push:
    branches:
    - master
    - dev
    - hotfix*
    paths:
    - src/**
    - build/**
    - forcebuild.txt
    - .github/workflows/*

# NOTE: Each step sets cwd back to git folder.
jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create build files & build
      run: cd src && ./creategameprojects
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: |
          game/zombie_master_reborn/bin/linux64/client.so
          game/zombie_master_reborn/bin/linux64/server.so

  build-windows:
    name: Build for Windows
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Run creategameprojects.bat
      run: cd src && ./creategameprojects.bat
    - name: Build
      run: msbuild src/zmr-games.sln -property:Configuration=Release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: |
          game/zombie_master_reborn/bin/x64/client.dll
          game/zombie_master_reborn/bin/x64/client.pdb
          game/zombie_master_reborn/bin/x64/server.dll
          game/zombie_master_reborn/bin/x64/server.pdb
