name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: echostuff
      run: echo $PWD
    - name: install_libs
      run: sudo apt install build-essential gcc-multilib g++-multilib
    - name: download_runtime
      run: sudo mkdir /valve
        | sudo wget http://media.steampowered.com/client/runtime/steam-runtime-sdk_latest.tar.xz
        | sudo tar xvf steam-runtime-sdk_latest.tar.xz
        | sudo mv steam-runtime-sdk_2013-09-05 /valve/steam-runtime
    - name: install_runtime
      run: cat steam-runtime-install.txt | /valve/steam-runtime/setup.sh
    - name: create_make_file
      run: cd mp/src
        | ./creategameprojects
    - name: make
      run: make -f zmr-games.mak | sudo /valve/steam-runtime/shell-i386.sh
